language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services: mysql

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer install --no-interaction

before_script:
  - mysql -e 'create database test_db; use test_db; source tests/setup.sql;'
  - cp tests/config.travis.php tests/config.php

script: ./vendor/bin/phpunit

after_success: ./vendor/bin/coveralls
