language: php

sudo: false

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.5.9
      env: setup=stable
    - php: 5.5.9
      env: setup=lowest

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-stable --prefer-lowest; fi

services: mysql

before_script:
  - mysql -e 'create database test_db; use test_db; source tests/setup.sql;'
  - cp tests/config.travis.php tests/config.php

script: ./vendor/bin/phpunit

after_success: ./vendor/bin/coveralls
